1. PROJECT TITLE - DEEPCSAT – ECOMMERCE CUSTOMER SATISFACTION SCORE PREDICTION.

2. PROJECT SUMMARY - 

    The project involved data cleaning, feature engineering, and encoding categorical variables using one-hot encoding. Exploratory Data Analysis (EDA) was conducted to identify patterns in customer interactions and satisfaction levels. Key insights revealed that returns and order-related queries generated the highest interaction volumes and that CSAT scores were highly imbalanced toward the highest rating.

    A neural network model was developed using TensorFlow and Keras to treat CSAT prediction as a multi-class classification problem. The model consisted of multiple dense layers with ReLU activation and a Softmax output layer to predict the five CSAT classes. Class weights were applied to address class imbalance during training.

    Model performance was evaluated using accuracy, precision, recall, F1-score, and confusion matrix analysis. The trained model was then prepared for deployment through a Streamlit application, enabling real-time CSAT prediction based on input interaction features.

    This project demonstrates an end-to-end machine learning workflow, including data preprocessing, exploratory analysis, model development, evaluation, and deployment for practical customer support analytics.

3. PROBLEM STATEMENT- 

    This project focuses on predicting Customer Satisfaction (CSAT) scores using Deep Learning Artificial Neural Networks (ANN). In the context of e-commerce, understanding customer satisfaction through their interactions and feedback is crucial for enhancing service quality, customer retention, and overall business growth. By leveraging advanced neural network models, we aim to accurately forecast CSAT scores based on a myriad of interaction-related features, providing actionable insights for service improvement.

4. LOADING AND CHECKING THE DATASET.

In [1]:
# Importing the necessary libraries
import pandas as pd
import warnings
import os
warnings.filterwarnings('ignore')

In [2]:
# To prevent truncating
pd.set_option('display.max_columns', None)

# Loading the dataset
df_unclean = pd.read_csv('../unclean_data/eCommerce_Customer_support_data.csv')

# Checking few sample rows of the dataframe
df_unclean.sample(7)

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
46165,3c0a0c6b-f25c-4a4b-b428-79bfec68a207,Inbound,Returns,Reverse Pickup Enquiry,NaN,1c8192b5-bdf4-455a-a8a6-cd6c4c68d8fe,NaN,17-08-23 18:51,17-08-23 19:27,17-Aug-23,NaN,NaN,NaN,NaN,Brittany Tran,Landon Tanaka,Emily Chen,>90,Morning,4
20438,f1eb84b3-d02f-4238-8f3a-8a9fb446ee5a,Inbound,Returns,Fraudulent User,the website is not at all user friendly,ea657d05-305e-4096-89fb-1cfed2dba815,NaN,09-08-23 08:45,09-08-23 10:50,09-Aug-23,NaN,NaN,NaN,NaN,Dana Taylor,Aiden Patel,John Smith,>90,Morning,5
57659,70c84978-8a8c-4ed2-9d8f-76d6c9ac7ce7,Inbound,Returns,Return request,NaN,9bca20f7-5e9b-45bd-a635-6836f6989fdc,NaN,22-08-23 20:50,22-08-23 20:53,22-Aug-23,NaN,NaN,NaN,NaN,Mr. Gregory Payne,Mia Patel,Jennifer Nguyen,On Job Training,Evening,5
54119,6dd83ab2-a0a2-43d0-8488-8e345008f1ef,Outcall,Order Related,Installation/demo,NaN,76bea5f5-c041-4c64-b836-bffb207a8331,NaN,20-08-23 22:22,21-08-23 08:38,21-Aug-23,NaN,NaN,NaN,NaN,Anthony Shaffer,Carter Park,Jennifer Nguyen,On Job Training,Evening,5
13924,1c8cbf75-a022-4895-b795-93229989be7d,Email,Returns,Damaged,NaN,09acddc6-293f-4c2a-bd5b-53a845245567,NaN,06-08-23 20:34,06-08-23 22:20,06-Aug-23,NaN,NaN,NaN,NaN,Dakota Collins,Logan Lee,Emily Chen,61-90,Evening,1
1257,985c1802-0bf5-49c1-b84a-d89e890f17c4,Inbound,Cancellation,Not Needed,Thanks??,6d070d80-1afb-427d-a2ab-686d97a279db,NaN,01-08-23 21:17,01-08-23 21:29,01-Aug-23,NaN,NaN,NaN,NaN,Jessica Santos,Elijah Yamaguchi,Emily Chen,31-60,Split,5
55196,b2f43ebd-9034-4c44-b406-35a4bf683a41,Inbound,Order Related,Invoice request,NaN,c3a8cf4c-bc7f-437e-a9d3-b7c195c187f2,NaN,21-08-23 15:08,21-08-23 15:11,21-Aug-23,NaN,NaN,NaN,NaN,Alan Sweeney,Madison Kim,Michael Lee,31-60,Evening,5

In [3]:
# Checking the info of df_unclean
df_unclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                85907 non-null  object
 1   channel_name             85907 non-null  object
 2   category                 85907 non-null  object
 3   Sub-category             85907 non-null  object
 4   Customer Remarks         28742 non-null  object
 5   Order_id                 67675 non-null  object
 6   order_date_time          17214 non-null  object
 7   Issue_reported at        85907 non-null  object
 8   issue_responded          85907 non-null  object
 9   Survey_response_Date     85907 non-null  object
 10  Customer_City            17079 non-null  object
 11  Product_category         17196 non-null  object
 12  Item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  Agent_name               85907 non-null  object
 15  Supervisor               85907 non-null  object
 16  Manager                  85907 non-null  object
 17  Tenure Bucket            85907 non-null  object
 18  Agent Shift              85907 non-null  object
 19  CSAT Score               85907 non-null  int64
dtypes: float64(2), int64(1), object(17)
memory usage: 13.1+ MB

In [4]:
# Checking the description of df_unclean
df_unclean.describe()

          Item_price  connected_handling_time    CSAT Score
count   17206.000000               242.000000  85907.000000
mean     5660.774846               462.400826      4.242157
std     12825.728411               246.295037      1.378903
min         0.000000                 0.000000      1.000000
25%       392.000000               293.000000      4.000000
50%       979.000000               427.000000      5.000000
75%      2699.750000               592.250000      5.000000
max    164999.000000              1986.000000      5.000000

In [5]:
# Checking the null values of df_unclean
df_unclean.isna().sum()

Unique id                      0
channel_name                   0
category                       0
Sub-category                   0
Customer Remarks           57165
Order_id                   18232
order_date_time            68693
Issue_reported at              0
issue_responded                0
Survey_response_Date           0
Customer_City              68828
Product_category           68711
Item_price                 68701
connected_handling_time    85665
Agent_name                     0
Supervisor                     0
Manager                        0
Tenure Bucket                  0
Agent Shift                    0
CSAT Score                     0
dtype: int64

In [6]:
# Removing columns that are either very sparse or those that won't be useful for predicting CSAT
df_unclean = df_unclean.drop(columns=['Unique id', 'Customer Remarks', 'Order_id', 'order_date_time', 'Customer_City', 'Product_category',
                                      'Item_price', 'connected_handling_time', 'Agent_name', 'Supervisor', 'Manager'])

# Checking rows of the updated dataframe
df_unclean.sample(5)

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Tenure Bucket,Agent Shift,CSAT Score
73491,Inbound,Feedback,UnProfessional Behaviour,27-08-23 14:28,27-08-23 14:39,27-Aug-23,On Job Training,Evening,5
70181,Inbound,Refund Related,Refund Enquiry,26-08-23 07:51,26-08-23 07:52,26-Aug-23,31-60,Morning,5
60838,Inbound,Payments related,Payment related Queries,23-08-23 13:07,23-08-23 13:09,23-Aug-23,On Job Training,Evening,5
6521,Inbound,Order Related,Installation/demo,03-08-23 23:18,03-08-23 23:28,03-Aug-23,31-60,Evening,3
83680,Inbound,Returns,Fraudulent User,31-08-23 10:49,31-08-23 14:27,31-Aug-23,>90,Morning,3

In [7]:
# Rechecking for null values
df_unclean.isnull().sum()

channel_name            0
category                0
Sub-category            0
Issue_reported at       0
issue_responded         0
Survey_response_Date    0
Tenure Bucket           0
Agent Shift             0
CSAT Score              0
dtype: int64

In [8]:
# Rechecking the info
df_unclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   channel_name          85907 non-null  object
 1   category              85907 non-null  object
 2   Sub-category          85907 non-null  object
 3   Issue_reported at     85907 non-null  object
 4   issue_responded       85907 non-null  object
 5   Survey_response_Date  85907 non-null  object
 6   Tenure Bucket         85907 non-null  object
 7   Agent Shift           85907 non-null  object
 8   CSAT Score            85907 non-null  int64
dtypes: int64(1), object(8)
memory usage: 5.9+ MB

In [9]:
# Changing the dtypes of Issue_reported at, issue_responded and Survey_response_Date columns
df_unclean['Issue_reported at'] = pd.to_datetime(df_unclean['Issue_reported at'], dayfirst=True)
df_unclean['issue_responded'] = pd.to_datetime(df_unclean['issue_responded'], dayfirst=True)
df_unclean['Survey_response_Date'] = pd.to_datetime(df_unclean['Survey_response_Date'], dayfirst=True)

In [10]:
# Checking the dtypes after changing
df_unclean.dtypes

channel_name                    object
category                        object
Sub-category                    object
Issue_reported at       datetime64[ns]
issue_responded         datetime64[ns]
Survey_response_Date    datetime64[ns]
Tenure Bucket                   object
Agent Shift                     object
CSAT Score                       int64
dtype: object

In [11]:
# Checking the first few rows
df_unclean.head()

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Tenure Bucket,Agent Shift,CSAT Score
0,Outcall,Product Queries,Life Insurance,2023-08-01 11:13:00,2023-08-01 11:47:00,2023-08-01,On Job Training,Morning,5
1,Outcall,Product Queries,Product Specific Information,2023-08-01 12:52:00,2023-08-01 12:54:00,2023-08-01,>90,Morning,5
2,Inbound,Order Related,Installation/demo,2023-08-01 20:16:00,2023-08-01 20:38:00,2023-08-01,On Job Training,Evening,5
3,Inbound,Returns,Reverse Pickup Enquiry,2023-08-01 20:56:00,2023-08-01 21:16:00,2023-08-01,>90,Evening,5
4,Inbound,Cancellation,Not Needed,2023-08-01 10:30:00,2023-08-01 10:32:00,2023-08-01,0-30,Morning,5

In [12]:
# Creating a new feature "responsetime"
df_unclean['responsetime'] = df_unclean['issue_responded'] - df_unclean['Issue_reported at']
df_unclean.head()

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Tenure Bucket,Agent Shift,CSAT Score,responsetime
0,Outcall,Product Queries,Life Insurance,2023-08-01 11:13:00,2023-08-01 11:47:00,2023-08-01,On Job Training,Morning,5,0 days 00:34:00
1,Outcall,Product Queries,Product Specific Information,2023-08-01 12:52:00,2023-08-01 12:54:00,2023-08-01,>90,Morning,5,0 days 00:02:00
2,Inbound,Order Related,Installation/demo,2023-08-01 20:16:00,2023-08-01 20:38:00,2023-08-01,On Job Training,Evening,5,0 days 00:22:00
3,Inbound,Returns,Reverse Pickup Enquiry,2023-08-01 20:56:00,2023-08-01 21:16:00,2023-08-01,>90,Evening,5,0 days 00:20:00
4,Inbound,Cancellation,Not Needed,2023-08-01 10:30:00,2023-08-01 10:32:00,2023-08-01,0-30,Morning,5,0 days 00:02:00

In [ ]:
# Changing the values of the 'responsetime' column to minutes
df_unclean['responsetime_in_mins'] = df_unclean['responsetime'].dt.total_seconds()/60

# Keeping only the rows that do not have any negative values in the 'responsetime_in_mins' column
df_unclean = df_unclean[df_unclean['responsetime_in_mins'] >= 0]

# Checking first few rows
df_unclean.head()

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Tenure Bucket,Agent Shift,CSAT Score,responsetime,responsetime_in_mins
0,Outcall,Product Queries,Life Insurance,2023-08-01 11:13:00,2023-08-01 11:47:00,2023-08-01,On Job Training,Morning,5,0 days 00:34:00,34.0
1,Outcall,Product Queries,Product Specific Information,2023-08-01 12:52:00,2023-08-01 12:54:00,2023-08-01,>90,Morning,5,0 days 00:02:00,2.0
2,Inbound,Order Related,Installation/demo,2023-08-01 20:16:00,2023-08-01 20:38:00,2023-08-01,On Job Training,Evening,5,0 days 00:22:00,22.0
3,Inbound,Returns,Reverse Pickup Enquiry,2023-08-01 20:56:00,2023-08-01 21:16:00,2023-08-01,>90,Evening,5,0 days 00:20:00,20.0
4,Inbound,Cancellation,Not Needed,2023-08-01 10:30:00,2023-08-01 10:32:00,2023-08-01,0-30,Morning,5,0 days 00:02:00,2.0

In [14]:
# Ordinally encoding the 'Tenure Bucket' column
tenure = {'On Job Training': 0,
          '0-30': 1,
          '31-60': 2,
          '61-90': 3,
          '>90': 4}

df_unclean['Tenure_Bucket_enc'] = df_unclean['Tenure Bucket'].map(tenure)

# Checking the first few rows
df_unclean.head()

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Tenure Bucket,Agent Shift,CSAT Score,responsetime,responsetime_in_mins,Tenure_Bucket_enc
0,Outcall,Product Queries,Life Insurance,2023-08-01 11:13:00,2023-08-01 11:47:00,2023-08-01,On Job Training,Morning,5,0 days 00:34:00,34.0,0
1,Outcall,Product Queries,Product Specific Information,2023-08-01 12:52:00,2023-08-01 12:54:00,2023-08-01,>90,Morning,5,0 days 00:02:00,2.0,4
2,Inbound,Order Related,Installation/demo,2023-08-01 20:16:00,2023-08-01 20:38:00,2023-08-01,On Job Training,Evening,5,0 days 00:22:00,22.0,0
3,Inbound,Returns,Reverse Pickup Enquiry,2023-08-01 20:56:00,2023-08-01 21:16:00,2023-08-01,>90,Evening,5,0 days 00:20:00,20.0,4
4,Inbound,Cancellation,Not Needed,2023-08-01 10:30:00,2023-08-01 10:32:00,2023-08-01,0-30,Morning,5,0 days 00:02:00,2.0,1

In [15]:
# Checking the info of the updated dataframe
df_unclean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82779 entries, 0 to 85906
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   channel_name          82779 non-null  object
 1   category              82779 non-null  object
 2   Sub-category          82779 non-null  object
 3   Issue_reported at     82779 non-null  datetime64[ns]
 4   issue_responded       82779 non-null  datetime64[ns]
 5   Survey_response_Date  82779 non-null  datetime64[ns]
 6   Tenure Bucket         82779 non-null  object
 7   Agent Shift           82779 non-null  object
 8   CSAT Score            82779 non-null  int64
 9   responsetime          82779 non-null  timedelta64[ns]
 10  responsetime_in_mins  82779 non-null  float64
 11  Tenure_Bucket_enc     82779 non-null  int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5), timedelta64[ns](1)
memory usage: 8.2+ MB

In [16]:
# Fixing the capitalisation issues of 'category' column
df_unclean['category'] = df_unclean['category'].str.title()

# Changing the dtype of 'responsetime_in_mins' column to int64
df_unclean['responsetime_in_mins'] = df_unclean['responsetime_in_mins'].astype(int)

In [17]:
# Omitting the columns that won't be necessary
df_clean = df_unclean.drop(columns=['Issue_reported at', 'issue_responded', 'Survey_response_Date', 'Tenure Bucket', 'responsetime'])

# Checking the rows of the new dataframe
df_clean.head()

,channel_name,category,Sub-category,Agent Shift,CSAT Score,responsetime_in_mins,Tenure_Bucket_enc
0,Outcall,Product Queries,Life Insurance,Morning,5,34,0
1,Outcall,Product Queries,Product Specific Information,Morning,5,2,4
2,Inbound,Order Related,Installation/demo,Evening,5,22,0
3,Inbound,Returns,Reverse Pickup Enquiry,Evening,5,20,4
4,Inbound,Cancellation,Not Needed,Morning,5,2,1

In [ ]:
# Making a folder to store the cleaned dataframe
os.makedirs('../clean_data', exist_ok=True)

In [19]:
# Storing both the clean and the unclean dataframe
df_unclean.to_csv('../unclean_data/df_unclean.csv', index=False)
df_clean.to_csv('../clean_data/df_clean.csv', index=False)